-- =============================================================================
-- Supabase Schema Setup for GTPinput (Consolidated)
-- 
-- INSTRUCTIONS:
-- 1. Go to your Supabase Project Dashboard -> SQL Editor
-- 2. Paste the contents of this file
-- 3. Click "Run"
-- 
-- This script creates the necessary tables and applies Row Level Security (RLS) policies
-- to ensure each user can only access and manage their own data.
-- =============================================================================

-- 1. Expenses Table
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  item text not null,
  amount numeric not null,
  category text default '其他',
  note text,
  source text default 'manual',
  user_id uuid references auth.users not null default auth.uid()
);

-- Enable Security
alter table public.expenses enable row level security;

-- Policies for Expenses
create policy "Enable insert for expenses" on public.expenses for insert with check (auth.uid() = user_id);
create policy "Enable select for expenses" on public.expenses for select using (auth.uid() = user_id);
create policy "Enable update for expenses" on public.expenses for update using (auth.uid() = user_id);
create policy "Enable delete for expenses" on public.expenses for delete using (auth.uid() = user_id);


-- 2. Budgets Table
create table public.budgets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  category text not null,
  amount numeric not null,
  color text default '#FF4B4B',
  icon text default '💰',
  user_id uuid references auth.users not null default auth.uid()
);

alter table public.budgets enable row level security;

-- Policies for Budgets
create policy "Enable insert for budgets" on public.budgets for insert with check (auth.uid() = user_id);
create policy "Enable select for budgets" on public.budgets for select using (auth.uid() = user_id);
create policy "Enable update for budgets" on public.budgets for update using (auth.uid() = user_id);
create policy "Enable delete for budgets" on public.budgets for delete using (auth.uid() = user_id);


-- 3. Recurring Rules Table
create table public.recurring_rules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  amount numeric not null,
  category text not null,
  frequency text not null, -- 'weekly', 'monthly', 'yearly'
  day integer not null,
  active boolean default true,
  last_run_date date,
  user_id uuid references auth.users not null default auth.uid()
);

alter table public.recurring_rules enable row level security;

-- Policies for Recurring Rules
create policy "Enable insert for recurring" on public.recurring_rules for insert with check (auth.uid() = user_id);
create policy "Enable select for recurring" on public.recurring_rules for select using (auth.uid() = user_id);
create policy "Enable update for recurring" on public.recurring_rules for update using (auth.uid() = user_id);
create policy "Enable delete for recurring" on public.recurring_rules for delete using (auth.uid() = user_id);
